### ISSUE TITLE
"Selfemode" Loginfehler

### ISSUE THREAD

**Issue by muenzberg-me** [FriendsOfREDAXO/maintenance#10]
Wenn man in seinem Template z.B. eine If Then Else mit `if ($addon->getConfig('frontend_aktiv') == 'Selfmade')` macht, funktioniert zwar die Ausgabe für normale User aber nicht das ich als Admin meine Seite sehe.

**Comment by skerbis** [comment]
Option wird entfernt bzw. umbenannt. Hier geht es nicht um die Sperren in den vorherigen Feldern.
