### ISSUE TITLE
Editor konfigurierbar machen.

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/maintenance#100]
**Feature description / Feature Beschreibung**

**Comment by alxndr-w** [comment]
Das blöde ist, der ist dann erst nach Speichern editierbar. Ich habe das Feature extra rausgenommen, kann es aber so umsetzen wie in meinen anderen Add-ons auch.

**Comment by skerbis** [comment]
Es ist ok wenn nach der Installation noch kein Editor gewählt ist und nicht irgendeiner vorkonfiguriert ist. Ich würde den Editor wie bei YForm per JSON Notation konfigurierter sehen.

**Comment by alxndr-w** [comment]
Ist es doch, per Config-Feld.
