### ISSUE TITLE
Wartungsmodus inaktiv, solange kein Passwort hinterlegt wurde

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/maintenance#104]
Der Wartungsmodus wird nicht aktiviert (Seite ist weiterhin komplett aufrufbar), solange kein Passwort zwingend angegeben wird.
Das soll sicher so nicht sein, da das Passwort nur optional ist.

Redaxo: 5.17.1
Maintenance: 3.0.0

**Comment by alxndr-w** [comment]
Für mich zum Nachvollziehen, warum kein Passwort hinterlegt war: Wurde beim Updaten das Passwort übernommen / war vorher keins hinterlegt / hast du das, was standardmäßig hinterlegt wird, wieder rausgelöscht?

**Comment by alxndr-w** [comment]
Das Problem ist einfach nachzuvollziehen: "Kein Passwort" entspricht dem abgefragten Secret:

https://github.com/FriendsOfREDAXO/maintenance/blob/538d3a1cdcf4b80d3c45920459d876f32cd630e4/lib/Maintenance.php#L109-L111

PR welcome
