### ISSUE TITLE
Eingeloggte "normale" Nutzer erhalten Wartungsscreen trotz Option "eingeloggte REDAXO-Benutzer haben weiterhin Zugriff" 

### ISSUE THREAD

**Issue by alexwenz** [FriendsOfREDAXO/maintenance#116]
Eingeloggte "normale" Nutzer erhalten Wartungsscreen trotz Option "eingeloggte REDAXO-Benutzer haben weiterhin Zugriff". Als Admin erhält man diesen nicht.

Maintenance-Version: 3.2.1
REDAXO: 5.17.1
PHP: 8.3.11 
Database: MariaDB 10.3.39

**Comment by ischfr** [comment]
Kann ich bestätigen. Die genannte Option scheint keinen Effekt zu haben?
Ob Passwort oder Geheim-URL macht auch keinen Unterschied.

Maintenance 3.2.1
REDAXO: 5.17.1
PHP: 8.2.25
Database: MariaDB 10.11.7

**Comment by alxndr-w** [comment]
Bitte PR bereitstellen mit Fix, wenn's schnell gelöst werden soll. Ich komme da dieses Jahr nicht mehr dazu.
