### ISSUE TITLE
Maintenance "light" Rolle für Redakteure?

### ISSUE THREAD

**Issue by ischfr** [FriendsOfREDAXO/maintenance#117]
Ich hatte meinen Redakteuren bisher immer auch die Rolle für das Maintenance-Addon gegeben, um so bei Bedarf die Site (bzw. das Frontend) schnell mal komplett sperren zu können.

Da die entsprechende Rolle das Addon komplett zugänglich macht, war das natürlich nicht ideal.
Die neue Version hat nun noch mehr Einstellmöglichkeiten und sogar Hilfetexte mit Code-Schnipseln zur Einbindung.
Die Einstellseite (Frontend-Reiter) ist dadurch inzwischen ziemlich lang geworden.

Könnte man hier evtl. eine zusätzliche Rolle realisieren, die Maintenance auf das absolute Minimum reduziert? 
Damit ein Redakteur damit das Frontend ein- und ausschalten kann. 
Evtl. noch mit Vergabe des Passworts, aber alles andere bleibt durch den Admin festgelegt?

Vielleicht wäre es auch sinnvoll, einen zusätzlichen ersten Tab zu machen, der einfach nur Toggle-Buttons für Maintenance Frontend an/aus und Backend an/aus enthält. Was meint Ihr?

**Comment by alxndr-w** [comment]
Finde ich gut!

Ich denke, ein PR dazu dürfte einfach sein:

1. `package.yml` erweitern um die Seite + zuweisen einer separaten Permission
2. in `/pages/` die `frontend.php` duplizieren in `frontend-light.php`
3. in `frontend-light.php` alle Einstellungen entfernen bis auf das Select zum Wartungsmodus.

**Comment by ischfr** [comment]
@alxndr-w sorry, das übersteigt leider meine Fähigkeiten.

**Comment by alxndr-w** [comment]
@ischfr es übersteigt deine Fähigkeiten, in der package.yml 2 statt einer Seite zu definieren und den Code aus der Einstellungs-Seite nochmal in eine 2. Seite zu kopieren?
