### ISSUE TITLE
Default Maintenance-Seite im FOR-Design mitliefern

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/maintenance#13]
Jemand Lust @elricco - vielleicht?

**Comment by staabm** [comment]
Ggf. Kann man sich an der enstehenden error seite fürs backend anlehnen

https://github.com/redaxo/redaxo/issues/1420#issuecomment-338165656

**Comment by skerbis** [comment]
Ich glaube es sollte doch eher eine durch den User individuell gestaltbare Seite sein, ggf. mit Logo des Betreibers der Seite.

**Comment by staabm** [comment]
elrico hat mir zugesagt zu unserem treffen das html für https://github.com/redaxo/redaxo/issues/1420#issuecomment-338165656 mitzubringen und dann kann man das hier ja auch nehmen

**Comment by skerbis** [comment]
ok

**Comment by skerbis** [comment]
<img width="1533" alt="Bildschirmfoto 2019-06-28 um 16 04 46" src="https://user-images.githubusercontent.com/791247/60348677-5c21cb80-99c0-11e9-9154-9b7c47cdf630.png">

@tbaddade @staabm 
So sieht Sie aktuell aus. 
Ist als Fragment realisiert.
Anregungen?

**Comment by Geri2017** [comment]
vl. noch `Wartungsmodus` zu `Maintenance mode` auf deutsch dazu?

**Comment by skerbis** [comment]
![Bildschirmfoto 2019-06-28 um 16 50 17](https://user-images.githubusercontent.com/791247/60350900-dbb19980-99c4-11e9-89ff-2ad255961cd0.png)
besser @Geri2017 ?

**Comment by Geri2017** [comment]
Perfekto!

**Comment by staabm** [comment]
Bis auf den tippfehler im wort Maintenance find ichs gut

**Comment by skerbis** [comment]
korrigiert und hiermit beendet
