### ISSUE TITLE
YRewrite-Multidomain

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/maintenance#15]
Auswählen für welche Domain die Sperre gelten soll.

**Comment by olien** [comment]
ha. genau das Issue wollte ich auch schreiben :-)

**Comment by skerbis** [comment]
PR welcome

**Comment by olien** [comment]
Wenn ich es könnte....

**Comment by skerbis** [comment]
Domains auslesen, select anbieten und dann abfragen?

**Comment by alexplusde** [comment]
+1

**Comment by skerbis** [comment]
@alexplusde machst du mir schon mal die Auswahlliste als Select fertig? Ich weiß du hast das was fertiges ;-)

**Comment by alexplusde** [comment]
Du meinst das hier? ;)

https://github.com/yakamara/redaxo_yrewrite/blob/master/README.md#%C3%BCbersicht-aller-domains-ausgeben

**Comment by alexplusde** [comment]
Allmählich bin ich davon überzeugt, dass YRewrite metadatenfähig werden muss. Vieles ließe sich darüber bequemer abwickeln, z.B. auch ein eigenes Maintenance-/Statusfeld.

**Comment by alexplusde** [comment]
https://github.com/yakamara/redaxo_yrewrite/issues/180

**Comment by skerbis** [comment]
Unabhängig von YRewrite. 
Domains können jetzt ausgeschlossen werden 
https://github.com/FriendsOfREDAXO/maintenance/releases/tag/2.6.0
