### ISSUE TITLE
Zugriff durch "interne" Crawler immer zulassen

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/maintenance#25]

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/seoinspector/issues/10
https://github.com/FriendsOfREDAXO/search_it/issues/214

**Comment by alexplusde** [comment]
gut, man müsste halt nen get-Parameter mitgeben können in den enstprechenden Addons.

**Comment by skerbis** [comment]
Ich denke ich mach's über die IP

**Comment by alexplusde** [comment]
funktioniert für dich. für andere vermutlich nicht :/

**Comment by skerbis** [comment]
Und wieso @alexplusde? Es funktioniert ja jetzt bereits, wenn du die IP des Servers hinzufügst

**Comment by skerbis** [comment]
Bei der Sperre können IPs angegeben werden.
