### ISSUE TITLE
Konflikt mit AddOn be_branding

### ISSUE THREAD

**Issue by helpy** [FriendsOfREDAXO/maintenance#26]
Hallo,

ich habe neben dem maintenance AddOn auch das AddOn https://github.com/danspringer/be_branding installiert. In be_branding habe ich ein Projekt-Logo hinzugefügt. Dieses Logo wird auch über der REDAXO-Login-Box angezeigt.

**Ist jedoch maintenance aktiviert (Frontend sperren) und ich bin nicht eingeloggt, dann wird das Logo auf die URL-Weiterleitung umgeleitet.**

Wenn ich wüsste, wo ich ansetzen soll, dann könnte ich ja versuchen, das selbst zu lösen. 
Ich habe zwar einen vorübergehenden Workaround gefunden, das ist aber keine saubere Lösung.
Hat jemand einen Tipp für mich, wo ich da ansetzen könnte?

**Comment by skerbis** [comment]
Das Logo wird über das Frontend aufgerufen. Da alles Frontendaktionen gesperrt sind, führt dies zur genannten Umleitung. be_branding sollte das Bild anders aufrufen.

**Comment by helpy** [comment]
Aaah! Danke. Ich habe wieder etwas gelernt.
Mit dem Backend und der Ausgabe für das Backend, hatte ich mich bisher noch nie beschäftigt.
