### ISSUE TITLE
statt config-Wert zu speichern in data-Verzeichnis ablegen

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/maintenance#29]
Das würde verhindern, dass bei Operationen wie Datenbank-Backup/Import der Wert flöten geht.

**Comment by skerbis** [comment]
Da das AddOn bei jedem Seitenaufruf eine solche Datei öffnen müsste, würde dies ggf. den Seitenaufbau verzögern, wenn maintenance nicht genutzt wird. Ich denke das ließe sich nur so regeln wenn man es in die config.yml von Redaxo schreibt.
Was denkst du @alxndr-w ?

**Comment by alxndr-w** [comment]
Ich hatte immer gehört, Filesystem sei schneller als DB?

**Comment by skerbis** [comment]
Mag sein, aber es bleibt das Problem, dass das AddOn nach dem db import wohl evtl. nicht mehr aktiv ist

**Comment by staabm** [comment]
Die frage ist nach dem use-case.

will man das maintenance mit import/export mit seinen settings mit umzieht, oder will man dass die settings eher pro instanz sind, egal welche seite/welchen stand man da drinnen importiert hat. Ich kann es aktuell nicht beurteilen

> Maintenance müsste zumindest in einer Grundversion in den Core?

ich denke um eine config datei ins „data“ verzeichnis zu schreiben braucht es nix maintenance spezisiches im core.. oder an was hast du dabei genau gedacht?

**Comment by skerbis** [comment]
@staabm wenn im maintenance Mode ein db Backup in importiert wird in dem maintenance nicht installiert war ist das maintenance addon wieder deinstalliert. - daran habe ich gedacht. Wenn man im Core einen einfachen Modus hätte könnte zumindest dieser beibehalten werden, weils in der config.yml des Cores aktiviert sein könnte

**Comment by skerbis** [comment]
Kurz nachgedacht, es wäre wohl der debug Mode der sich dafür anbietet und das Frontend sperren könnte im livebetrieb

**Comment by alxndr-w** [comment]
@skerbis das löst das Problem der Deinstallation nicht.

Dann müsste es vermutlich ein System-Addon sein.

**Comment by skerbis** [comment]
Debug mode  könnte zumindest selbst ein maintenance Modus haben das das Frontend sperrt. Mein Addon könnte sich dann wieder einklinken

**Comment by alxndr-w** [comment]
Okay
1. Es löst das Problem nicht – wenn dein Addon durch den Import-Vorgang deinstalliert ist, wird das Frontend nach dem Import-Vorgang nicht gesperrt
2. Es verführt dazu, den Debug-Modus auf einer Live-Seite zu aktivieren, um das Frontend zu sperren
3. Das Frontend lässt sich als Entwickler im Debug-Modus in einer dev-Umgebung nicht mehr aufrufen, ohne angemeldet zu sein.

Ich finde, Maintenance und Debug müssen 2 getrennte Themen bleiben, aber es wäre gut, wenn der Wartungsmodus ein Core-Feature würde imho.

**Comment by skerbis** [comment]
Ich denke wir kommen hier nicht weiter ohne einen core-seitigen maintenance mode.

**Comment by alxndr-w** [comment]
Wäre das denn gewünscht?

**Comment by skerbis** [comment]
Ein minimaler Maintenance mode wäre schon ok für den Core, finde ich. Darauf könnte dieses AddOn aufbauen und weitere Optionen bieten. - Es ändert dann aber auch nichts daran dass dieses AddOn nach einem DB-Import deaktiviert wäre. 
Daher close ich hier.
