### ISSUE TITLE
Einzelne Seiten ausschließen

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/maintenance#38]

**Comment by Geri2017** [comment]
Moin Thomas,
wäre das die Möglichkeit bei einer bereits online stehenden Seite, einzelne gesperrte Seiten für Kunden per link, bzw. code anschauen zu können? 
Wenn ja, dann MEEEGAA!
LG, Geri

**Comment by skerbis** [comment]
Ja so ist es gedacht

**Comment by skerbis** [comment]
Werde ich wohl nicht umsetzen.
