### ISSUE TITLE
Rewrite der Logik in boot.php 

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/maintenance#41]

**Comment by christophboecker** [comment]
Ich weiß jetzt grade nicht, was Du mit em Issue meinst. Ich bin aber - wollte mir mal ansehen wie das Addon arbeitet - darüber gestolpert, dass es auch dann im BE CSS/JS lädt, wenn es inaktiv ist. Braucht es das wirklich?

**Comment by skerbis** [comment]
Das gehört dazu

**Comment by skerbis** [comment]
Also das css brauchst du für die Settings

**Comment by christophboecker** [comment]
Ich begrenze schon mal auf ausgewählte Pages oder Addons, was ja im Backend simpel ist, und include dann Scripte oder rufe statische Methoden auf. SO ähnlich, mal eben zusammengekloppt
```php
switch( rex_be_controller::getCurrentPagePart(1) ) {
    case 'content':
        // Beispiel für "include"
        include_once( 'extensions/extension_structure.php' );
        break;
    case 'mediapool':
        // Beispiel für "class::method"
       \myaddon\boot::mediapool();
        break;
    case 'myaddon':
    case 'yform':
    case 'project':
        // Beispiel für direkten Code
        rex_view::addJsFile( $this->getAssetsUrl('script.min.js') );
        rex_view::addJsFile( $this->getAssetsUrl('style.min.js') );
        break;
 }
```

**Comment by skerbis** [comment]
Danke. Schauma ma

**Comment by alxndr-w** [comment]
#81 done
