### ISSUE TITLE
Admin sperrt sich im Backend aus, wenn man die Benutzeridentität wechselt

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/maintenance#44]
Der Admin kann sich während der Wartungssitzung im Backend aussperren, wenn er versehentlich auf "Benutzeridentät wechseln" klickt.
Dies passiert, wenn man Redakteure aus dem Backend aussperrt.

Hier wäre es z.B. besser, wenn die Funktion zum Wechseln der Identität deaktiviert wird, solange der Wartungsmodus aktiv ist und der Admin angemeldet ist.

**Comment by skerbis** [comment]
Danke. 
erledigt https://github.com/FriendsOfREDAXO/maintenance/commit/7f7dec4f0c9643063ddce39e74127a1c2b581c80
Kommt im nächsten Release, gerne den aktuellen Stand testen
