### ISSUE TITLE
Einzelne Seiten / Artikel mit Passwort schützen

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/maintenance#45]
In einem Multidomain-Projekt muss ich auf Artikel-Basis einzelne Seiten freischalten oder unter Passwortschutz stellen können.

Es gibt einige Möglichkeiten, das im Template mit Metainfos zu lösen. Wäre es jedoch auch gewünscht, wenn sich maintenance mit einem Plugin wie YCom, YRewrite und Co. in die Artikel-Bearbeiten-Ansicht einhängt und ein Einstellungsfeld zur Verfügung stellt?

Ich sehe es nicht bei YCom, da hier die Basis Benutzer/Rollen/Loginformulare sind und nicht dauerhafte Secrets zum Blick hinter die Kulissen.

**Comment by skerbis** [comment]
Probier mal das AddOn locked
https://github.com/klxm/locked

**Comment by skerbis** [comment]
Ich prüfe ob ich das Locked AddOn hier als PlugIn einbaue

**Comment by alxndr-w** [comment]
duplicate #38
