### ISSUE TITLE
Auswahl/Änderung Response Code 

### ISSUE THREAD

**Issue by alexwenz** [FriendsOfREDAXO/maintenance#49]
Wir nutzen das Addon auch für Preview/Staging/Dev-Seiten. Standardmäßig wird der Response-Code 503 "HTTP_SERVICE_UNAVAILABLE" verwendet, der für eine vorrübergehende "Maintenance" auch perfekt ist. 

Die Staging-Seiten/Domains bleiben jedoch zumeist immer geschützt. Dort wäre 403 "HTTP_FORBIDDEN" die besser Wahl. 

Was denkt Ihr darüber? Wäre eine Option denkbar, in der man das auswählen kann?

**Comment by skerbis** [comment]
@alexwenz leg los 👍🏻

**Comment by skerbis** [comment]
@alexwenz ?

**Comment by alexwenz** [comment]
Nächstes Wochenende ;-)
