### ISSUE TITLE
Einzelne Domains aus YRewrite sperren mit individuellem Artikel

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/maintenance#50]
Ich betreibe hier mehrere Domains via YRewrite. Es wäre ein großartiges Feature, wenn es möglich wäre, den Mode für einzelne Domains anzulegen. 
Daran anknüpfend (eigentlich ein separater Feature Request) wäre es toll, wenn pro Domain dann nicht ein statisches HTML ausgegeben würde, sondern ein definierter Artikel.

**Comment by skerbis** [comment]
Hallo @cukabeka
Aktuell geht es nur anders rum. Du kannst auswählen welche Domains nicht gesperrt sein sollen. 
> wenn pro Domain dann nicht ein statisches HTML ausgegeben würde
das könntest du durch das Überschreiben des Fragmentes selbst lösen und dort abfragen. Ggf. in Kombination mit dem  Domainsettings-AddOn

**Comment by alxndr-w** [comment]
@cukabeka möchtest du die Version `3.0.0` testen, die wird das können.

**Comment by cukabeka** [comment]
Hi @alxndr-w Danke dass ihr die Funktion berücksichtigt und eingebaut habt. Ich habe leider gerade kein geeignetes System am Laufen - dort wo ich das gut testen kann, stehen noch ein paar fragile Updates aus, sobald ich das System hochgezogen habe, teste ich das gerne.
