### ISSUE TITLE
IDEE: Zeitgesteuerte Wartungen

### ISSUE THREAD

**Issue by bitshiftersgmbh** [FriendsOfREDAXO/maintenance#51]
Wir bauen zunehmend komplexere Tools mit Redaxo. Mal treiben sich die Leute dafür im FE rum und es funzt mit YCom, mal im BE mit dem üblichen User-Login. Das Ding bei solchen Installationen ist, das Menshcen da in irgendwelche Datenbanktabellen Daten via Formularen eingeben. Ist nun einer dabei, einen neuen Datensatz anzulegen und klimpert 30min lang Daten dort rein und in der Zwischenzeit schalte ich den Wartungsmodus ein, verliert derjenige alle Eingaben (und die wertvolle Zeit) und wird etwas genervt sein.

Da wäre es cool, wenn man wie z.B. bei populären Games Wartungen zeitlich ankündigen könnte. Im Prinzip braucht es dafür lediglich einen Datetimepicker mehr im Verwaltungsbereich. Ab 1h vor Beginn (oder wie auch immer) würde oben einen Overlay über den Header ragen, das deutlich sagt `Wartung beginnt in HH:mm`, wobei das per JS dann entsprechend runterzählt und sollte man dann noch auf der Seite sein, diese neulädt oder ajax-neulädt, um die Wartungsseite anzuzeigen.

Wichtig ist dabei, dass Nutzer von einer geplanten Wartung (Updates, neue Features, Bugfixes) nicht überrascht werden, sondern sich zeitlich darauf einstellen können. Der Aufwand dafür sollte recht moderat sein und dabei mehr "Professionalität" in dieses Feature bringen.  Starten würde ich zunächst nur für den BE-Wartungsmodus, da dort die Einbindung von eigenem JS etc. unkomplizierter ist.

-----

Wo wir bei Professionalisierung sind ;) ... ich fände in dem Kontext noch 2 weitere Sachen toll:
* Beschreibungstext (textarea) mit individueller Wartungsmeldung (`"Wir räumen Ihren vermüllten Medienpool auf. Haben Sie gefälligst Geduld!"` z.B.)
* Angabe einer angedachten Dauer der Downtime
* alle 3 hier nun genannten Felder selbstverständlich alle optional

Evtl. ist das ja auch ne coole Integration weil sinnvoll und passend für https://github.com/FriendsOfREDAXO/minibar (dann eben nicht mehr im Header als Overlay sondern Minibar Entry)

**Comment by skerbis** [comment]
Ich denke, dass die Person die gerade an einem langen Text (30 Minuten) rumhampelt, die Info auch nicht sehen wird. 
Hier bräuchte es eine Push-Notification oder sowas in REDAXO.

**Comment by skerbis** [comment]
Ich werde es nicht realisieren. PR Welcome.

**Comment by alxndr-w** [comment]
Kommt in #81, bitte testen @bitshiftersgmbh
