### ISSUE TITLE
Bei Ausschluss von Domains funktioniert Sperrung allgemein nicht mehr

### ISSUE THREAD

**Issue by danspringer** [FriendsOfREDAXO/maintenance#52]
Wenn in den auszuschliessenden Domains eine Domain (oder mehrere) eingetragen sind, funktioniert die Sperrung auch bei den Domains nicht mehr, die nicht auf der Allow-List stehen, also den Domains die gesperrt sein sollten. Es sind dann also alle Domains erreichbar.

<details>
<summary>System report (REDAXO 5.13.2, PHP 8.0.18, MariaDB 10.3.34)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.13.2     |

| PHP           |            |
| ------------: | :--------- |
|       Version | 8.0.18     |
|       OPcache | yes        |
|        Xdebug | no         |

| Database      |                 |
| ------------: | :-------------- |
|       Version | MariaDB 10.3.34 |
| Character set | utf8mb4         |

| Server        |              |
| ------------: | :----------- |
|            OS | Linux        |
|          SAPI | fpm-fcgi     |
|     Webserver | nginx/1.21.5 |

| Request       |                      |
| ------------: | :------------------- |
|       Browser | Chrome/101.0.4951.54 |
|      Protocol | HTTP/2.0             |
|         HTTPS | yes                  |

| Packages                   |            |
| -------------------------: | :--------- |
|                    adminer | 1.9.2      |
|                     backup | 2.8.0      |
|                be_branding | 1.7        |
|                   be_style | 3.0.1      |
|        be_style/customizer | 3.0.1      |
|            be_style/redaxo | 3.0.1      |
|                   be_tools | 1.7.4      |
|                    bloecks | 3.1.1      |
|           bloecks/cutncopy | 3.1.1      |
|                    cronjob | 2.8.2      |
|                  developer | 3.9.0      |
|                 focuspoint | 4.0.0      |
|                   icecoder | 3.0.0      |
|                    install | 2.9.3      |
|                maintenance | 2.7.3      |
|              massif_minify | 1.3.1      |
|                     matomo | 1.2.1      |
|                     mblock | 3.4.4      |
|              media_manager | 2.12.1     |
|                  mediapool | 2.11.2     |
|                   metainfo | 2.8.4      |
|             mf_lastchanges | 0.9        |
|                      mform | 6.1.2      |
|                 mform/docs | 1.1        |
|                     minify | 2.2        |
|              minify_images | 2.1.2      |
|                  phpmailer | 2.11.1     |
|                    project | dev        |
|                   redactor | 2.3.0      |
|                      sprog | 1.3.0      |
|                  structure | 2.13.2     |
|          structure/content | 2.13.2     |
|                      theme | 1.3.3      |
|                   ui_tools | 1.2.1      |
| ui_tools/jquery-minicolors | 2.4.0      |
|                   uploader | 2.3.0      |
|                        url | 2.0.0-dev  |
|                      users | 2.8.2      |
|                      yform | 4.0.0      |
|                yform/email | 4.0.0      |
|              yform/manager | 4.0.0      |
|                yform/tools | 4.0.0      |
|      yform_spam_protection | 1.2.1      |
|                   yrewrite | 2.8.3      |
|   yrewrite_domain_settings | 2.0.2      |
|            yrewrite_scheme | 3.6.1      |

</details>

**Comment by skerbis** [comment]
Siehe 2.7.4
