### ISSUE TITLE
Warning: Undefined array key "HTTP_HOST"

### ISSUE THREAD

**Issue by tyrant88** [FriendsOfREDAXO/maintenance#55]
![Zwischenablage-3](https://user-images.githubusercontent.com/1277494/171826443-e191242d-d282-483e-a4e5-d88035537312.jpg)

angemeckert wird:

https://github.com/FriendsOfREDAXO/maintenance/blob/master/boot.php#L71

$_SERVER['HTTP_HOST']

**Comment by skerbis** [comment]
Funzt es bei Dir mit:  $_SERVER['SERVER_NAME']);  ?

**Comment by tyrant88** [comment]
Problem ist: Ich kann es nicht reproduzieren. Es muss ja durch einen Aufruf kommen, bei dem der host-Header nicht gesetzt ist...
Muss wohl irgendein Hintergrund-Aufruf sein. Vielleicht console.
PHP_SAPI == 'cli' ?

SERVER_NAME oder HTTP_HOST wird auch so immer gern diskutiert, was man nehmen soll.
Wird hier aber ncihts ändern denke ich.

Pragmatische Lösung wäre ```if (isset($_SERVER['HTTP_HOST']) ```

**Comment by tyrant88** [comment]
streiche die letzte Bemerkung

**Comment by skerbis** [comment]
Ich mache folgendes: Ich werde wieder zurückstellen auf $_SERVER['SERVER_NAME']; - das funktionierte über Jahre gut. 
$_SERVER['HTTP_HOST'] scheint es nur bei einem Request über den Browser zu geben. 
Leider kann ich es auf meinen Systemen nicht reproduzieren, da beide bei mir immer gesetzt sind.

**Comment by tyrant88** [comment]
klingt gut.

**Comment by skerbis** [comment]
Mal schauen habe gerade ne andere Lösung 👍🏻 ...

**Comment by skerbis** [comment]
@tyrant88 
Habe es jetzt so gelöst (hoffentlich) 

https://github.com/FriendsOfREDAXO/maintenance/blob/4c42fd45fb4a655bf6817eccb716ccde35dca094/boot.php#L72-L80

Bitte testen

**Comment by tyrant88** [comment]
Code läuft durch, aber wie ich oben schon sagte, die Warning kann ich nicht reproduzieren.

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/maintenance/releases/tag/2.7.7
