### ISSUE TITLE
Wartungsmodus aktiv und nvBeTheme Addon: Login Logo unter /redaxo/ wird nicht angezeigt

### ISSUE THREAD

**Issue by godsdog** [FriendsOfREDAXO/maintenance#58]
Wenn der Wartungsmodus aktiv ist und im nvBeTheme Addon ein Login Logo ausgewählt ist, wird dieses im Backend Login nicht mehr angezeigt. In der Console wird beim Bild **503 Service Unavailable** zurück gegeben.

Ich denke, dass ist grundsätzlich auch richtig so, dass keine Medienpool Daten öffentlich zugänglich sind, wenn der Wartungsmodus aktiv ist. Evtl. kann man dann für diese Datei eine Ausnahme einrichten.

**Comment by skerbis** [comment]
Es wird eine neue Config mit Whitelist für Medien geben.

**Comment by skerbis** [comment]
wird wohl eher ein extensionpoint

**Comment by skerbis** [comment]
Hi @godsdog hast du Lust zu testen? 

https://github.com/FriendsOfREDAXO/maintenance/pull/69/commits/b09e8487b55686416985c64300aa3e77f4eabb5b

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/maintenance/releases

**Comment by alxndr-w** [comment]
@godsdog könntest du das nochmal mit der 3.0.0 testen?

**Comment by godsdog** [comment]
@alxndr-w Gerne wann bzw. wo kann ich die 3.0er downloaden?
