### ISSUE TITLE
`secret` reicht nicht, um auf `sitemap.xml` von YRewrite zuzugreifen

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/maintenance#63]
**Description / Beschreibung**
In https://github.com/alexplusde/cache_warm_up und https://github.com/alexplusde/link_checker/ möchte ich die `sitemap.xml` von YRewrite abrufen, um zu erfahren, welche URLs es auf der Website oder den Websites gibt.

Leider reicht es nicht, der `example.org/sitemap.xml` den GET-Parameter `?secret=...` dranzuhängen. Stattdessen wird die "Weiterleitung zu" ausgeführt.

Wenn man das Frontend mit `secret` so aufruft, dann kommt man auch an die `sitemap.xml`. Das hilft aber mir hier allerdings nicht.

**Comment by skerbis** [comment]
schon mal mit der IP versucht? Die IP vom Server?

**Comment by alxndr-w** [comment]
Du meinst, die IP in der whitelist freizugeben? Hat nicht geklappt.

**Comment by skerbis** [comment]
hmm

**Comment by skerbis** [comment]
@alxndr-w  bitte das testen: https://github.com/FriendsOfREDAXO/maintenance/commit/5c3acedf9e544b04e8492a7510ea2504ac142b3a
