### ISSUE TITLE
Warning: Undefined array key "REQUEST_URI"

### ISSUE THREAD

**Issue by thorol** [FriendsOfREDAXO/maintenance#65]
**Description / Beschreibung**
redaxo/src/addons/maintenance/boot.php | Zeile 14 wirft folgenden Fehler bei Verwendung der Redaxo Console:
Undefined array key "REQUEST_URI"
https://github.com/FriendsOfREDAXO/maintenance/blame/master/boot.php#L14

Dadurch werden im entsprechenden Intervall bei jedem Aufruf der Console Fehler-E-Mails versendet. 

**Affected versions / Verwendete Versionen**

REDAXO: 5.14.2
PHP: 8.1.13
Database:
Browser: 
AddOns: maintenance: 2.8.6

**Did it whoops? / Whoops erhalten?**

**Comment by skerbis** [comment]
Da würde mich aktuell interessieren warum es bei dir nicht gesetzt ist

**Comment by thorol** [comment]
Ich denke, da es über die console/cli verwendet wird.

**Comment by thorol** [comment]
Alles andere ist dort mit rex::isFrontend() oder rex::isBackend() geklammert.

**Comment by skerbis** [comment]
Ah übersehen console. Fix kommt
