### ISSUE TITLE
Auf Domains einschränken statt erlauben

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/maintenance#83]
**Feature description / Feature Beschreibung**
Statt in einer Multidomain-Umgabung 10 Domains zu erlauben (und damit nicht zu sehen, welche im Wartungsmodus sind), sollte man eher Fragen, auf welchen Hosts und/oder YRewrite-Domains der Wartungsmodus gelten soll.

![image](https://github.com/FriendsOfREDAXO/maintenance/assets/3855487/ceb6ee5c-0719-4d15-9228-957512ddcaab)

**Comment by skerbis** [comment]
Es gibt für beide Szenarien plausible Gründe ... ich bin hier unentschlossen. 
Die jetzige Variante hat sich über Jahre bewährt.

**Comment by alxndr-w** [comment]
Das möchte ich dann nicht mehr für 3.0 beantworten und hinten anstellen.

**Comment by alxndr-w** [comment]
Ich möchte das im Zweifel lieber zugunsten anderer Features lassen.
