### ISSUE TITLE
Multidomain-Fähigkeit

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/maintenance#9]
Wenn mehrere Domains verwendet werden, muss man sich unter jeder Domain vorher im Redaxo einloggen. Kann man das vereinfachen?

/cc Frage von @pixelpaul

**Comment by IngoWinter** [comment]
wer ist eigentlich dieser @PixelPaul? imho kann mans nicht vereinfachen, da der zugriff über die session geregelt wird. dafür brauchste einen cookie, cookies sind an domains gebunden.

**Comment by skerbis** [comment]
@alexplusde heute kommt ein Release mit geheimer url. (gab gestern noch ein Problem). 
Allerdings nur global, nicht je Domain - aber das sollte Dein Problem lösen.

**Comment by alexplusde** [comment]
Ok, wie in Slack angekündigt würden würden wir das am Montag gleich ausprobieren.

**Comment by skerbis** [comment]
Jede domain muss halt einmal mit dem entsprechenden code aufgerufen werden. Die Links gebt ihr dem Kunden ja, dann müssen die ja nur klicken.

**Comment by alexplusde** [comment]
Den Code verwenden wir auch selbst, wenn wir auch selbst, wenn wir in einer Multi-Domain arbeiten.

Funktioniert btw.
