### ISSUE TITLE
Default-Value im Feld "IP-Whiteliste" fehlerhaft

### ISSUE THREAD

**Issue by dpf-dd** [FriendsOfREDAXO/maintenance#90]
Zunächst einmal danke für die neue Version 3.0 :)

Habe soeben mal die 3.0dev durchgeguckt - läuft soweit.
Aber bei den Einstellungen hat sich ein kleiner Fehlerteufel eingeschlichen: Da steht ein `.` vor der IP-Adresse und ich vermute der Punkt gehört da nicht hin...

Ansonsten: Alles top! :)

**Comment by skerbis** [comment]
Kann ich im aktuellen Repostand nicht bestätigen @alxndr-w ?

**Comment by alxndr-w** [comment]
Müsste ein `,` gewesen sein und kann sein, dass dies bei der Migration des Wertes von 2.x auf 3.x in der update.php passiert.

**Comment by dpf-dd** [comment]
Hmm, grad nochmal bei einem anderen Projekt von 2.9.x aktualisiert auf 3.0dev...
Resultat: Jetzt steht meine IP-Adresse NICHT mehr automatisch in der Whitelist. Also ist das auch kein . (oder ,) - das Zeichen taucht auch nicht auf, wenn ich meine IP manuell eingebe und speichere.

Fehler ist also nicht mehr reproduzierbar :D

**Comment by alxndr-w** [comment]
Das möchte ich nochmal prüfen.

**Comment by dpf-dd** [comment]
OK... Habs nochmal bei einem Projekt als NEU-Installation probiert... Da ist der Fehler wieder :)

<img width="430" alt="Bildschirmfoto 2024-07-08 um 15 06 17" src="https://github.com/FriendsOfREDAXO/maintenance/assets/10958385/6d2af814-1721-40bf-b8a9-64edff0138a3">

Fazit: Es tritt bei einer Neu-Installation auf und NICHT beim Update...

**Comment by skerbis** [comment]
bitte mal die aktuelle Github-Version nehmen.

**Comment by dpf-dd** [comment]
Jo, schaut besser aus... 

<img width="496" alt="Bildschirmfoto 2024-07-08 um 15 13 03" src="https://github.com/FriendsOfREDAXO/maintenance/assets/10958385/14439d4d-3f71-4f8d-88de-7f5832d32bc7">

👍
