### ISSUE TITLE
Obwohl YRewrite-Domain freigegeben ist es gesperrt

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/maintenance#92]
<img width="787" alt="Bildschirmfoto 2024-07-09 um 09 24 49" src="https://github.com/FriendsOfREDAXO/maintenance/assets/791247/55dca293-0791-4bd7-b2ee-895de0f3e6ef">

**Comment by alxndr-w** [comment]
Wegen #83 Ich fände es generell sinnvoller, wenn es umgekehrt ist: Wenn Maintenance aktiv ist, dann auf folgenden Domains...

das ist kognitiv einfacher, zu verstehen, was man sperrt - als was trotz Sperrung wieder erlaubt ist, quasi wie doppelte Verneinung.

Ich würde das gerne noch vor 3.0.0 umdrehen.

**Comment by skerbis** [comment]
Sehe es anders: Eigentlich sollte zunächst alles gesperrt werden. Das Entsperren ist nur eine Ausnahme. Wenn an der Seite eh gearbeitet wird, sind in 90% der Fälle sicher alle Domains davon betroffen. Daher ist mir die Positiv-Liste lieber. 

Szenario: 

Website gesperrt mir Geheim-URL und Weiterleitung
-> Freigabe einer Domain in Maintenance zu der weitergeleitet wird. 
= Individuelle Not- oder Minimal-Website :-)

**Comment by alxndr-w** [comment]
Mein Szenario:

Multidomain, ein neues Projekt kommt an Bord - nur dieses muss gesperrt sein, andere n Domains sollen weiter wie gehabt funktionieren.

**Comment by skerbis** [comment]
Kommt bei beiden Szenarien auf die Menge der Domains an. Da der Abschnitt Ausnahmen heißt würde ich es jetzt so lassen. Vor allem weil auch die klassische Domainliste eine Positiv-Liste ist.

**Comment by skerbis** [comment]
Da das angesprochene Issue gelöst ist. Close ich das hier. Änderungen am Verhalten dann besser in einem neuen Issue
