### ISSUE TITLE
Müssen die Icons sein? (3.0.0-dev1)

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/maintenance#94]
Sieht irgendwie sehr verspielt ausfinde ich

![image](https://github.com/FriendsOfREDAXO/maintenance/assets/330516/4c675573-bffd-4a57-bcfa-992a7f71c246)

**Comment by olien** [comment]
![image](https://github.com/FriendsOfREDAXO/maintenance/assets/330516/5f43f892-de74-4d64-9efd-7c9c4ee8f882)

**Comment by skerbis** [comment]
Da stimmt doch bei dir was nicht? 

<img width="573" alt="Bildschirmfoto 2024-07-09 um 11 56 36" src="https://github.com/FriendsOfREDAXO/maintenance/assets/791247/2ac37a70-a435-4bb3-8d0d-8a37af9050fb">

**Comment by skerbis** [comment]
zu den Emojis: @alxndr-w können wir evtl. FontAwesome-Icons nutzen?

**Comment by alxndr-w** [comment]
Font-Awesome-Icons funktionieren leider nicht innerhalb von select.

**Comment by olien** [comment]
Können die dann ersatzlos weg? Sieht ja aus wie ein Kaugummiautomat ;-)

**Comment by olien** [comment]
Safari Mac

**Comment by olien** [comment]
Die versetzten icons in den Tabs meinte ich gar nicht. das ist meine Schuld (find die aber da auch überflüssig)

**Comment by alxndr-w** [comment]
Ich würde gerne die Sinnhaftigkeit nicht am persönlichen Geschmack festmachen. Ich finde es nützlich, gleich überfliegen zu können, was eingestellt ist.

Diskussion kann gerne wieder geöffnet werden, bisher zu wenig Äußerungen.
