### ISSUE TITLE
Textfeld auf 100% Breite (3.0.0-dev1)

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/maintenance#95]
**Feature description / Feature Beschreibung**

![image](https://github.com/FriendsOfREDAXO/maintenance/assets/330516/ad300d0a-1e73-4c40-abd7-a76998722c8a)

**Comment by skerbis** [comment]
<img width="1296" alt="Bildschirmfoto 2024-07-09 um 11 55 09" src="https://github.com/FriendsOfREDAXO/maintenance/assets/791247/093e79ee-3b63-4e08-b068-37099f535dda">

Ist es doch

**Comment by alxndr-w** [comment]
Achtung, bei der Installation wird ein neuer Config-Wert gesetzt, sodass man, wenn man möchte, den Editor seiner Wahl festlegen kann. Interessant wäre zu wissen, warum das bei @olien nicht geklappt hat. Hast du die Version installiert oder nur drübergebügelt?

**Comment by skerbis** [comment]
@alxndr-w wo legt man denn den Editor fest?  ...

**Comment by alxndr-w** [comment]
Aktuell nur in der rex_config, da es keine einheitliche Möglichkeit gibt. Wenn kein Editor gesetzt ist, sollte natürlich trotzdem `class="form-control"` ausgegeben werden.

**Comment by skerbis** [comment]
im default ist doch form-control drin. Dennoch sollte man den Editor konfigurieren können. So bringt es nichts.

**Comment by olien** [comment]
Hab n Update gemacht...
