### ISSUE TITLE
IP Wird nicht angezeigt (3.0.0-dev1)

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/maintenance#96]
![image](https://github.com/FriendsOfREDAXO/maintenance/assets/330516/ef53a732-a938-495b-bd64-e65d7a619c5d)

**Comment by skerbis** [comment]
Lokale IP?

**Comment by skerbis** [comment]
Kann ich gerade nicht reproduzieren

**Comment by olien** [comment]
Lokal / MAMP. Kann an mit liegen...

**Comment by skerbis** [comment]
::1 ist localhost unter ipv6 also richtig.
