### ISSUE TITLE
Liste erlaubter YRewriet Domains (3.0.0-dev1)

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/maintenance#97]
Unklar und unnötig wenn nur eine Domain existiert - oder?

![image](https://github.com/FriendsOfREDAXO/maintenance/assets/330516/d5eba876-9dd2-44ba-adce-119457af3988)

**Comment by olien** [comment]
gleiches gilt für "Liste erlaubter Domains"  - oder?

**Comment by skerbis** [comment]
Bei Yrewrite gebe ich dir Recht. Bei dem 2. Feld wissen wir nicht wie es die Person gelöst hat und ob überhaupt die Website mit anderen Domains aufgerufen werden kann.
