### ISSUE TITLE
AddOn Icon wieder einfärben wenn aktiv (3.0.0-dev1)

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/maintenance#98]
![image](https://github.com/FriendsOfREDAXO/maintenance/assets/330516/2b1df945-60e9-4a8c-885b-1e709707bc94)

**Comment by skerbis** [comment]
Die neue Variante zeigt an ob Backend und oder Frontend gesperrt sind. 
Aus meiner Sicht eine Verbesserung 

<img width="316" alt="Bildschirmfoto 2024-07-09 um 12 02 57" src="https://github.com/FriendsOfREDAXO/maintenance/assets/791247/ca94b16a-e03e-4103-b11a-6a61526fd999">

**Comment by skerbis** [comment]
@olien bitte gerne den aktuellen GitHub-Stand testen. Beta1 folgt in Kürze
